[build]
builder = "dockerfile"

[deploy]
startCommand = "./start.sh"
healthcheckPath = ""
healthcheckTimeout = 0
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "sandbox"